### ISSUE TITLE
Serialisation of a corpus

### ISSUE THREAD

**Issue by claudius108** [compenguy/ngrammatic#8]
Hi,

Thanks for this very nice library! It recognizes very well "tattvacintam" when the corpus contains "???avaci??am".

My question is that if such a corpus could be stored on disk. I would like to index some strings and use the corpus in the browser, with the library compiled to Webassembly.

Best regards!
Claudius Teodorescu

**Comment by compenguy** [comment]
It would be possible.  The most storage-efficient serialization of a corpus is just the list of words, from which the full corpus can be rebuilt.  The most cpu-efficient serialization is the full mappings of words-to-ngrams and ngrams-to-words.  Which means the Serialize trait is easy, but to implement the Deserialize trait we would need a key translation function.

In order to solve the Deserialize problem, we would need to make a breaking change to make the key translation function optional, and add methods to set a key translation function after the fact.

**Comment by claudius108** [comment]
Thank you!

I have a list of words with question marks instead of diacritics. I will
test the first approach, if the list is not that large, and I will let you
know about the results.

All the best,
Claudius

**Comment by LucaCappelletti94** [comment]
I have implemented the serde serialization/deserialization by swapping the boxed function with chainable key transformers. See pull request #10

**Comment by claudius108** [comment]
Thank you!

**Comment by LucaCappelletti94** [comment]
I just finished adding the necessary extra bells and whistles to [trie-rs](https://github.com/LucaCappelletti94/trie-rs) and I will be testing shortly how much memory we can save by switching from the hashmap to that. Will keep you posted. Until @compenguy consider merging my pull request, in the meantime you can use my fork here: https://github.com/LucaCappelletti94/ngrammatic/tree/master

**Comment by claudius108** [comment]
Hi!


I think this can be also useful: https://crates.io/crates/fst

I am using it for browser-based search engines. It allows fast regex
search, prefix search, and more.

Claudius
